### ISSUE TITLE
Empty tag for required fields

### ISSUE THREAD

**Issue by timendum** [NicolasLM/atoma#2]
Hi,
I think the validation on the source is a little too strict, for example if a `description` tag is present but empty in the channel section of an rss feed, atoma should not exit with an error in my opinion.

An example https://www.giornalettismo.com/feed

Thanks

**Comment by NicolasLM** [comment]
Hey,
You are right, when I started this project I was foolish enough to believe that most feeds would be compliant with the specifications. Now that I'm aware of it I try to relax constrains when I encounter a feed that doesn't parse.

Anyway, it should be fixed now.
