### ISSUE TITLE
Atom feed reader wrong error message

### ISSUE THREAD

**Issue by amirouche** [NicolasLM/atoma#3]
Try to parse a RSS feed with the ATOM reader leads to a dubious message:

```python
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import atoma

In [2]: import requests

In [3]: url = 'https://hyperdev.fr/feed.xml'

In [4]: response = requests.get(url)

In [5]: atoma.parse_atom_bytes(response.content)
---------------------------------------------------------------------------
FeedParseError                            Traceback (most recent call last)
<ipython-input-5-14e8e040a115> in <module>()
----> 1 atoma.parse_atom_bytes(response.content)

~/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/atoma/atom.py in parse_atom_bytes(data)
    275     """Parse an Atom feed from a byte-string containing XML data."""
    276     root = parse_xml(BytesIO(data)).getroot()
--> 277     return _parse_atom(root)

~/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/atoma/atom.py in _parse_atom(root, parse_entries)
    222 def _parse_atom(root: Element, parse_entries: bool=True) -> AtomFeed:
    223     # Mandatory
--> 224     id_ = get_text(root, 'feed:id', optional=False)
    225 
    226     # Optional

~/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/atoma/utils.py in get_text(element, name, optional)
     49 
     50 def get_text(element: Element, name, optional: bool=True) -> Optional[str]:
---> 51     child = get_child(element, name, optional)
     52     if child is None:
     53         return None

~/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/atoma/utils.py in get_child(element, name, optional)
     39         raise FeedParseError(
     40             'Could not parse RSS channel: "{}" required in "{}"'
---> 41             .format(name, element.tag)
     42         )
     43 

FeedParseError: Could not parse RSS channel: "feed:id" required in "rss"

In [6]: atoma.__version__
Out[6]: '0.0.9'
```

That is misleading:

> FeedParseError: Could not parse RSS channel: "feed:id" required in "rss"

**Comment by NicolasLM** [comment]
Hey,

Thanks for the report, I updated the message to be less confusing.

On a side note, if you want to parse RSS, Atom and JSON feeds and you are not interested in the details of all of them, you can check the simple API.

It is an undocumented module that levels out the differences between theses formats and give an easier to use interface. It is the one that I use in my feed reader. https://github.com/NicolasLM/atoma/blob/master/atoma/simple.py

**Comment by tm553** [comment]
Hi there, I'm having an issue using the atom bytes parse tool. Unfortunately the following code yields an error; 

`import requests
import atoma

response = requests.get('https://api.icis.com/v1/entities/ref-data/currency', auth=('username@email.com', 'password'))

a = atoma.parse_atom_bytes(response.content)`

This yields the following error; 

ValueError: 'application/vnd.icis.iddn.entity+xml' is not a valid AtomTextType

If you're able to provide any assistance that would be brilliant!

**Comment by NicolasLM** [comment]
Hi @tm553, could you create a new issue for your problem and paste a redacted version of the file you're trying to parse. It is behind an auth wall so it's impossible for me to check what is inside.
