### ISSUE TITLE
long_description_content_type in setup.py

### ISSUE THREAD

**Issue by impredicative** [NicolasLM/atoma#6]
At this time, the readme is not properly formatted on [pypi](https://pypi.org/project/atoma/). The `setup()` function in `setup.py` may benefit from `long_description_content_type='text/x-rst'`. That's according to the packaging [docs](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata). After this change, please release to pypi to confirm it works.

**Comment by NicolasLM** [comment]
Fixed, in fact it was broken because multiple links had the same title (`specification`):

```
$ twine check dist/*
Checking distribution dist/atoma-0.0.14-py3-none-any.whl: Failed
The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 2: Warning: Duplicate explicit target name: "specification".
```

Thank you for taking the time to report this issue.
