### ISSUE TITLE
Project status inquiry

### ISSUE THREAD

**Issue by impredicative** [NicolasLM/atoma#7]
Is the project dead or is it still alive? I filed an issue over a month ago, and it received no attention. I just want to know if it's worth using this project.

**Comment by NicolasLM** [comment]
I'll let you be the judge of that: I consider the code to be mostly stable for my use case, so far I've used it to parse over a million articles successfully.

As the issue your raised is mostly cosmetic, I'm sure you can understand that it is very low priority on my todo list.

**Comment by impredicative** [comment]
Cosmetic details matter because they show how committed one is to a project, not because of the cosmetic details themselves. It takes under five minutes to resolve that issue and push out a new release, but apparently it's asking for too much.

**Comment by NicolasLM** [comment]
> It takes under five minutes to resolve that issue and push out a new release, but apparently it's asking for too much.

I am sorry that my pet project made available for free does not match your quality standards.

**Comment by impredicative** [comment]
The misformatted text is analogous to a [broken window](https://en.wikipedia.org/wiki/Broken_windows_theory).

From https://blog.codinghorror.com/the-broken-window-theory/ :
> neglect accelerates the rot faster than any other factor
