### ISSUE TITLE
atoma/atom.py", line 22

### ISSUE THREAD

**Issue by micheleberardi** [NicolasLM/atoma#8]
Hi
when i run my script i got this error
`
Traceback (most recent call last):
  File "import_shopify.py", line 15, in <module>
    import atoma
  File "/usr/lib/python3.4/site-packages/atoma/__init__.py", line 1, in <module>
    from .atom import parse_atom_file, parse_atom_bytes
  File "/usr/lib/python3.4/site-packages/atoma/atom.py", line 22
    text_type: str = attr.ib()
             ^
SyntaxError: invalid syntax
`
THIS MY SCRIPT
`
import atoma, requests

def shopify(url):
    response = requests.get(url)
    feed = atoma.parse_atom_bytes(response.content)
    return feed

url = "https://www.mydomain.com/all.atom"
feed = shopify(url)
print(feed)
`

Thanks in advance for your help

**Comment by NicolasLM** [comment]
Hi,

It's because the project uses features of Python 3.6, so it's not compatible with 3.4.

**Comment by micheleberardi** [comment]
Hi Nicolas
ops :) sorry but thanks very much for your help
now everything works great
